---

require:
- rubocop-rake
- rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
  - "**/*.erb"
  - spec/**/*
  - vendor/**/*
  - examples/**/*
  - lib/vanagon/platform/defaults/*

Capybara/MatchStyle:
  Enabled: true

Capybara/NegationMatcher:
  Enabled: true

Capybara/SpecificActions:
  Enabled: true

Capybara/SpecificFinders:
  Enabled: true

Capybara/SpecificMatcher:
  Enabled: true

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: true

Gemspec/RequireMFA:
  Enabled: false

Layout/AccessModifierIndentation:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Layout/BlockAlignment:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/ConditionPosition:
  Enabled: false

Layout/DefEndAlignment:
  Enabled: false

Layout/DotPosition:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationStyle:
  Enabled: false

Layout/IndentationWidth:
  Enabled: true

Layout/LeadingCommentSpace:
  Enabled: false

Layout/LineContinuationLeadingSpace:
  Enabled: true

Layout/LineContinuationSpacing:
  Enabled: true

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2

Layout/ParameterAlignment:
  Enabled: false

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAfterMethodName:
  Enabled: true

Layout/SpaceAfterNot:
  Enabled: true

Layout/SpaceAfterSemicolon:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

Layout/SpaceBeforeComma:
  Enabled: true

Layout/SpaceBeforeComment:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: true

Layout/SpaceBeforeSemicolon:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: true

Lint/AmbiguousOperatorPrecedence:
  Enabled: true

Lint/AmbiguousRange:
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/ConstantOverwrittenInRescue:
  Enabled: true

Lint/Debugger:
  Enabled: false

Lint/DeprecatedClassMethods:
  Enabled: false

Lint/DeprecatedConstants:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateMagicComment:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/EmptyInPattern:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Lint/Loop:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/NonAtomicFileOperation:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/RedundantStringCoercion:
  Enabled: false

Lint/RefinementImportMethods:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Lint/RequireRangeParentheses:
  Enabled: true

Lint/RequireRelativeSelfPath:
  Enabled: true

Lint/RescueException:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/SuppressedException:
  Enabled: true

Lint/SymbolConversion:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/UselessRescue:
  Enabled: true

Lint/UselessRuby2Keywords:
  Enabled: true

Lint/Void:
  Enabled: true

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CollectionLiteralLength:
  Enabled: true

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: true

Naming/AccessorMethodName:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Enabled: true

Naming/BlockForwarding:
  Enabled: true

Naming/ClassAndModuleCamelCase:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Naming/MethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

RSpec/BeEq:
  Enabled: true

RSpec/BeNil:
  Enabled: true

RSpec/ChangeByZero:
  Enabled: true

RSpec/DuplicatedMetadata:
  Enabled: true

RSpec/ExcessiveDocstringSpacing:
  Enabled: true

RSpec/FactoryBot/ConsistentParenthesesStyle:
  Enabled: true

RSpec/FactoryBot/FactoryNameStyle:
  Enabled: true

RSpec/FactoryBot/SyntaxMethods:
  Enabled: true

RSpec/IdenticalEqualityAssertion:
  Enabled: true

RSpec/NoExpectationExample:
  Enabled: true

RSpec/PendingWithoutReason:
  Enabled: true

RSpec/Rails/AvoidSetupHook:
  Enabled: true

RSpec/Rails/HaveHttpStatus:
  Enabled: true

RSpec/Rails/InferredSpecType:
  Enabled: true

RSpec/Rails/MinitestAssertions:
  Enabled: true

RSpec/Rails/TravelAround:
  Enabled: true

RSpec/RedundantAround:
  Enabled: true

RSpec/SkipBlockInsideExample:
  Enabled: true

RSpec/SortMetadata:
  Enabled: true

RSpec/SubjectDeclaration:
  Enabled: true

RSpec/VerifiedDoubleReference:
  Enabled: true

Rspec/BeforeAfterAll:
  Enabled: false

Rspec/ExampleLength:
  Enabled: false

Rspec/HookArgument:
  Enabled: false

Rspec/MultipleMemoizedHelpers:
  Enabled: false

Security/CompoundHash:
  Enabled: true

Security/Eval:
  Enabled: true

Security/IoMethods:
  Enabled: true

Style/AccessModifierDeclarations:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/Alias:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: true

Style/ArrayIntersect:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/Attr:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/CharacterLiteral:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassCheck:
  Enabled: false

Style/ClassMethods:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/CollectionCompact:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/CommandLiteral:
  EnforcedStyle: percent_x

Style/CommentAnnotation:
  Enabled: false

Style/ComparableClamp:
  Enabled: true

Style/ConcatArrayLiterals:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Style/DirEmpty:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/EmptyHeredoc:
  Enabled: true

Style/EmptyLiteral:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/EndlessMethod:
  Enabled: true

Style/EnvHome:
  Enabled: true

Style/EvenOdd:
  Enabled: true

Style/FetchEnvVar:
  Enabled: false

Style/FileEmpty:
  Enabled: true

Style/FileRead:
  Enabled: true

Style/FileWrite:
  Enabled: false

Style/For:
  Enabled: true

Style/FormatString:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashConversion:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/IfWithSemicolon:
  Enabled: true

Style/InPatternThen:
  Enabled: true

Style/Lambda:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/MagicCommentFormat:
  Enabled: true

Style/MapCompactWithConditionalBlock:
  Enabled: true

Style/MapToHash:
  Enabled: true

Style/MapToSet:
  Enabled: true

Style/MethodCallWithoutArgsParentheses:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/MinMaxComparison:
  Enabled: true

Style/ModuleFunction:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: true

Style/MultilineIfThen:
  Enabled: true

Style/MultilineInPatternThen:
  Enabled: true

Style/MultilineTernaryOperator:
  Enabled: true

Style/NegatedIf:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/NegatedWhile:
  Enabled: true

Style/NestedFileDirname:
  Enabled: true

Style/NestedTernaryOperator:
  Enabled: true

Style/Next:
  Enabled: false

Style/NilComparison:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/NonNilCheck:
  Enabled: true

Style/Not:
  Enabled: true

Style/NumberedParameters:
  Enabled: true

Style/NumberedParametersLimit:
  Enabled: true

Style/NumericLiteralPrefix:
  Enabled: false

Style/NumericLiterals:
  Enabled: true

Style/ObjectThen:
  Enabled: true

Style/OneLineConditional:
  Enabled: true

Style/OpenStructUse:
  Enabled: false

Style/OperatorMethodCall:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: true

Style/PerlBackrefs:
  Enabled: false

Style/Proc:
  Enabled: true

Style/QuotedSymbols:
  Enabled: true

Style/RaiseArgs:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/RedundantCondition:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: true

Style/RedundantDoubleSplatHashBraces:
  Enabled: true

Style/RedundantEach:
  Enabled: true

Style/RedundantException:
  Enabled: true

Style/RedundantHeredocDelimiterQuotes:
  Enabled: true

Style/RedundantInitialize:
  Enabled: true

Style/RedundantPercentQ:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RedundantSelfAssignmentBranch:
  Enabled: true

Style/RedundantStringEscape:
  Enabled: true

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Enabled: true

Style/SafeNavigation:
  Enabled: false

Style/SelectByRegexp:
  Enabled: true

Style/SelfAssignment:
  Enabled: true

Style/Semicolon:
  Enabled: true

Style/SignalException:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringChars:
  Enabled: true

Style/StringLiterals:
  Enabled: false

Style/SwapValues:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/UnlessElse:
  Enabled: true

Style/VariableInterpolation:
  Enabled: true

Style/WhenThen:
  Enabled: false

Style/WhileUntilDo:
  Enabled: true

Style/WhileUntilModifier:
  Enabled: false

Style/WordArray:
  Enabled: false
