SHELL = <%=  @platform.shell %>

<%- merged_environment.to_a(" := ").each do |var| -%>
export <%= var %>
<%- end -%>

tempdir := $(shell <%= @platform.mktemp %> 2>/dev/null)
workdir := $(PWD)

all: file-list-before-build <%= package_name %>

<%= package_name %>: <%= @name %>-<%= @version %>.tar.gz
	<%= generate_package.join("\n\t") %>

file-list-before-build:
<%- if dirnames.empty? -%>
	touch file-list-before-build
<%- else -%>
	(<%= @platform.find %> -H "<%= dirnames.join('" "') %>" 2>/dev/null || <%= @platform.find %> "<%= dirnames.join('" "') %>" 2>/dev/null) | <%= "xargs -I[] cygpath --mixed --long-name --absolute [] |" if @platform.is_windows? %> <%= @platform.sort %> | uniq > file-list-before-build
<%- end -%>

file-list-after-build: <%= @components.map {|comp| comp.name }.join(" ") %>
<%- if dirnames.empty? -%>
	touch file-list-after-build
<%- else -%>
	(<%= @platform.find %> -H "<%= dirnames.join('" "') %>" 2>/dev/null || <%= @platform.find %> "<%= dirnames.join('" "') %>" 2>/dev/null) | <%= "xargs -I[] cygpath --mixed --long-name --absolute [] |" if @platform.is_windows? %> <%= @platform.sort %> | uniq > file-list-after-build
<%- end -%>

<%= @name %>-<%= @version %>.tar.gz: file-list <%= @cleanup ? 'cleanup-components' : '' %>
	<%= pack_tarball_command %>

file-list: file-list-before-build <%= @name %>-project
	comm -23 file-list-after-build file-list-before-build > file-list
	comm -23 file-list-after-build file-list-before-build | <%= @platform.sed %> -e 's/\(^.*[[:space:]].*$$\)/"\1"/g' > file-list-for-rpm

<%- if @version_file -%>
<%= @version_file.path %>:
	echo <%= @version %> > '<%= @version_file.path %>'
<%- end -%>

<%- if @bill_of_materials -%>
<%= @bill_of_materials.path %>:
	mkdir -p '<%= @bill_of_materials.path %>'
	mv bill-of-materials '<%= @bill_of_materials.path %>'
<%- end -%>

<%- dirnames.each do |dir| -%>
<%= dir %>: file-list-before-build
	mkdir -p '<%= dir %>'
<%- end %>

<%- if @cleanup -%>
cleanup-components: <%= @components.map {|comp| "#{comp.name}-cleanup" }.join(" ") %>
	touch cleanup-components
<%- end -%>

<%= @name %>-project: <%= dirnames.join(' ') %> <%= @version_file ? @version_file.path : '' %> <%= @bill_of_materials ? @bill_of_materials.path : '' %> file-list-after-build
	touch <%= @name %>-project

<%- @components.each do |comp| -%>
<%= comp.rules(self, @platform).to_s %>
<%- end -%>

clean: <%= @components.map {|comp| "#{comp.name}-clean" }.join(" ") %>

clobber: <%= @components.map {|comp| "#{comp.name}-clobber" }.join(" ") %>

.PHONY: clean clobber  <%= @components.map {|comp| "#{comp.name}-clean #{comp.name}-clobber" }.join(" ") %>
