<% dirnames = get_directories.map {|d| d.path } %>

tempdir := $(shell mktemp -d 2>/dev/null || mktemp -d -t 'tmp')

all: <%= package_name %>

<%= package_name %>: <%= @name %>-<%= @version %>.tar.gz
	<%= generate_package.join("\n\t") %>

file-list-before-build:
<%- if dirnames.empty? -%>
	touch file-list-before-build
<%- else -%>
	(find -L <%= dirnames.join(' ') %> -type f 2>/dev/null || find <%= dirnames.join(' ') %> -follow -type f) | sort > file-list-after-build
<%- end -%>

file-list-after-build: <%= @components.map {|comp| comp.name }.join(" ") %>
<%- if dirnames.empty? -%>
	touch file-list-after-build
<%- else -%>
	(find -L <%= dirnames.join(' ') %> -type f 2>/dev/null || find <%= dirnames.join(' ') %> -follow -type f) | sort > file-list-after-build
<%- end -%>

<%= @name %>-<%= @version %>.tar.gz: file-list
	<%= pack_tarball_command %>

file-list: <%= dirnames.join(' ') %> <%= @name %>-project
	comm -23 file-list-after-build file-list-before-build > file-list
	comm -23 file-list-after-build file-list-before-build | sed -e 's/\(^.*\s.*$$\)/"\1"/g' > file-list-for-rpm

<%- dirnames.each do |dir| -%>
<%= dir %>:
	mkdir -p <%= dir %>
<%- end %>

<%= @name %>-project: file-list-after-build
	touch <%= @name %>-project

<%- @components.each do |comp| -%>
<%= comp.name %>: <%= list_component_dependencies(comp).join(" ") %> <%= comp.name %>-install

<%= comp.name %>-unpack: file-list-before-build
	<%= comp.extract_with %>
	touch <%= comp.name %>-unpack

<%= comp.name %>-patch: <%= comp.name %>-unpack
	<%- unless comp.patches.empty? -%>
		cd <%= comp.dirname %>; \
		<%- comp.patches.each do |patch| -%>
			<%= @platform.patch %> -p1 < ../patches/<%= File.basename(patch) %>
		<%- end -%>
	<%- end -%>
	touch <%= comp.name %>-patch

<%= comp.name %>-configure: <%= comp.name %>-patch
	cd <%= comp.dirname %>; \
	<%= comp.configure.join(";\\\n\t") %>
	touch <%= comp.name %>-configure

<%= comp.name %>-build: <%= comp.name %>-configure
	cd <%= comp.dirname %>; \
	<%= comp.build.join(";\\\n\t") %>
	touch <%= comp.name %>-build

<%= comp.name %>-install: <%= comp.name %>-build
	cd <%= comp.dirname %>; \
	<%= comp.install.join(";\\\n\t") %>
	touch <%= comp.name %>-install

<%= comp.name %>-clean:
	[ -d <%= comp.dirname %> ] && cd <%= comp.dirname %>; \
	<%= @platform[:make] %> clean
	<%- ["configure", "build", "install"].each do |type| -%>
	[ -e <%= comp.name %>-<%= type %> ] && rm <%= comp.name %>-<%= type %>
	<%- end -%>

<%= comp.name %>-clobber: <%= comp.name %>-clean
	[ -d <%= comp.dirname %> ] && rm -r <%= comp.dirname %>
	[ -e <%= comp.name %>-unpack ] && rm <%= comp.name %>-unpack

<%- end -%>

clean: <%= @components.map {|comp| "#{comp.name}-clean" }.join(" ") %>

clobber: <%= @components.map {|comp| "#{comp.name}-clobber" }.join(" ") %>

.PHONY: clean clobber  <%= @components.map {|comp| "#{comp.name}-clean #{comp.name}-clobber" }.join(" ") %>
